import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import BootstrapComponentJs from "./components/bootstrap/js/bootstrap-componentJs";
import './index.css'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Holy Gpt",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <BootstrapComponentJs />
    </html>
  );
}
